### ISSUE TITLE
CAdvisor is crashing

### ISSUE THREAD

**Issue by posix4e** [signalfx/cadvisor-integration#29]
Cadvisor crashity crash

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x79e71e]
goroutine 25 [running]:
github.com/signalfx/cadvisor-integration/vendor/github.com/signalfx/metricproxy/dp/dpsink.(*EmptyMetricFilter).FilterDatapoints(0xc820129c00, 0xc8204261a0, 0x32, 0x32, 0x0, 0x0, 0x0)
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/signalfx/metricproxy/dp/dpsink/filter.go:19 +0xce
github.com/signalfx/cadvisor-integration/vendor/github.com/signalfx/metricproxy/protocol/signalfx.(*Forwarder).AddDatapoints(0xc820129b80, 0x7f471348b5f0, 0xc82000a520, 0xc8204261a0, 0x32, 0x32, 0x0, 0x0)
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/signalfx/metricproxy/protocol/signalfx/signalfxforwarder.go:296 +0x103
main.(*scrapWorkCache).waitAndForward.func1.1(0xc820417400, 0xc820417410, 0xc8200788a0, 0x7f471348b5f0, 0xc82000a520, 0xc8204261a0, 0x32, 0x32)
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:621 +0xa1
main.(*scrapWorkCache).waitAndForward.func1(0x0)
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:624 +0x74
main.(*scrapWorkCache).waitAndForward.func2(0xc8200788a0, 0xc820418f00, 0xc8204229c0, 0xc82041ab60)
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:639 +0xff
created by main.(*scrapWorkCache).waitAndForward
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:645 +0x28c
goroutine 1 [chan receive]:
main.(*prometheusScraper).main(0xc8201da350, 0x12a05f200, 0x45d964b800, 0x0, 0x0)
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:476 +0x852
main.main.func1(0xc8201cd7a0)
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:268 +0x8cf
github.com/signalfx/cadvisor-integration/vendor/github.com/codegangsta/cli.(*App).Run(0xc8201cd560, 0xc82000a230, 0x1, 0x1, 0x0, 0x0)
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/codegangsta/cli/app.go:180 +0x1028
main.main()
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:277 +0xe0f
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
goroutine 5 [chan receive]:
github.com/signalfx/cadvisor-integration/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x19f1620)
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/golang/glog/glog.go:882 +0x67
created by github.com/signalfx/cadvisor-integration/vendor/github.com/golang/glog.init.1
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/golang/glog/glog.go:410 +0x297
goroutine 16 [IO wait]:
net.runtime_pollWait(0x7f47162ff190, 0x72, 0xc82000a150)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201d3170, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201d3170, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201d3110, 0xc82025a000, 0x8000, 0x8000, 0x0, 0x7f47162f3050, 0xc82000a150)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026268, 0xc82025a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201eaf60, 0x7f47162ff250, 0xc820026268, 0x5, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82009f8c0, 0x13a5f17, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82009f8c0, 0xc820212000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7f47162ff6c0, 0xc82009f8c0, 0xc8200f1708, 0xc820212000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8201f1d40, 0xc820212000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820193800)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820193800, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200f16b0)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78
goroutine 34 [select]:
net/http.(*persistConn).writeLoop(0xc8200f16b0)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d
goroutine 19 [select]:
reflect.rselect(0xc82022b360, 0x5, 0x5, 0xc820078ae0, 0x5)
    /usr/local/go/src/runtime/select.go:650 +0x11f
reflect.Select(0xc82042e000, 0x5, 0x8, 0x32, 0x0, 0x0, 0x0, 0x1)
    /usr/local/go/src/reflect/value.go:1998 +0x282
main.(*scrapWorkCache).waitAndForward(0xc8200788a0)
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:649 +0x2e6
main.(*prometheusScraper).main.func1(0xc8200788a0, 0xc820078900)
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:415 +0x25
created by main.(*prometheusScraper).main
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:417 +0x72f
goroutine 20 [select]:
github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool.(*WorkPool).workRoutine(0xc820422900, 0x0)
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool/workpool.go:262 +0x2c0
created by github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool.New
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool/workpool.go:175 +0x185
goroutine 21 [select]:
github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool.(*WorkPool).workRoutine(0xc820422900, 0x1)
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool/workpool.go:262 +0x2c0
created by github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool.New
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool/workpool.go:175 +0x185
goroutine 22 [select]:
github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool.(*WorkPool).queueRoutine(0xc820422900)
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool/workpool.go:293 +0x302
created by github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool.New
    /go/src/github.com/signalfx/cadvisor-integration/vendor/github.com/goinggo/workpool/workpool.go:179 +0x1bc
goroutine 23 [chan receive]:
main.(*prometheusScraper).main.func2(0xc820422940, 0xc8200788a0, 0xc820422900)
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:424 +0x58
created by main.(*prometheusScraper).main
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:431 +0x7b7
goroutine 24 [chan receive]:
main.(*prometheusScraper).main.func3(0xc820422980, 0xc8201f0500, 0xc8201da350, 0xc8200788a0)
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:437 +0x9e
created by main.(*prometheusScraper).main
    /go/src/github.com/signalfx/cadvisor-integration/cmd/cadvisortosfx/main.go:474 +0x816
goroutine 36 [IO wait]:
net.runtime_pollWait(0x7f47162ff0d0, 0x72, 0xc82000a150)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82041aca0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82041aca0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82041ac40, 0xc820438000, 0x1000, 0x1000, 0x0, 0x7f47162f3050, 0xc82000a150)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200262c8, 0xc820438000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f47162ff250, 0xc8200262c8, 0xc8203ca268, 0xc820438000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8203d32c0, 0xc820438000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8202f3200)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202f3200, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8203ca210)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78
goroutine 37 [select]:
net/http.(*persistConn).writeLoop(0xc8203ca210)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d
goroutine 27 [IO wait]:
net.runtime_pollWait(0x7f47162ff010, 0x72, 0xc82000a150)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820375a30, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820375a30, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203759d0, 0xc820415000, 0x1000, 0x1000, 0x0, 0x7f47162f3050, 0xc82000a150)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82007e0f0, 0xc820415000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f47162ff250, 0xc82007e0f0, 0xc8200f1f48, 0xc820415000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820420a80, 0xc820415000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820079380)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820079380, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200f1ef0)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78
goroutine 28 [select]:
net/http.(*persistConn).writeLoop(0xc8200f1ef0)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d
goroutine 39 [IO wait]:
net.runtime_pollWait(0x7f47162fef50, 0x72, 0xc82000a150)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82041b3a0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82041b3a0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82041b340, 0xc820452000, 0x1000, 0x1000, 0x0, 0x7f47162f3050, 0xc82000a150)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026300, 0xc820452000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f47162ff250, 0xc820026300, 0xc8203ca3c8, 0xc820452000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8203d3840, 0xc820452000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8202f3800)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8202f3800, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8203ca370)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78
goroutine 40 [select]:
net/http.(*persistConn).writeLoop(0xc8203ca370)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d
goroutine 30 [IO wait]:
net.runtime_pollWait(0x7f47162fee90, 0x72, 0xc82000a150)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820375db0, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820375db0, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820375d50, 0xc82043b000, 0x1000, 0x1000, 0x0, 0x7f47162f3050, 0xc82000a150)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82007e150, 0xc82043b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f47162ff250, 0xc82007e150, 0xc820446108, 0xc82043b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8204212a0, 0xc82043b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8200799e0)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200799e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8204460b0)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78
goroutine 31 [select]:
net/http.(*persistConn).writeLoop(0xc8204460b0)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d
goroutine 33 [IO wait]:
net.runtime_pollWait(0x7f47162fedd0, 0x72, 0xc82000a150)
    /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82041b560, 0x72, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82041b560, 0x0, 0x0)
    /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82041b500, 0xc820455000, 0x1000, 0x1000, 0x0, 0x7f47162f3050, 0xc82000a150)
    /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82007e168, 0xc820455000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f47162ff250, 0xc82007e168, 0xc8203ca478, 0xc820455000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8204213e0, 0xc820455000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820079da0)
    /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820079da0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8203ca420)
    /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:685 +0xc78
goroutine 50 [select]:
net/http.(*persistConn).writeLoop(0xc8203ca420)
    /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
    /usr/local/go/src/net/http/transport.go:686 +0xc9d
```

**Comment by jk0** [comment]
This crash is the result of running the docker image.

**Comment by mdubbyap** [comment]
Thanks for reporting this. Looks like a nil was in the array of datapoints for some reason.  We'll take a look and get back to you as we can.

**Comment by jk0** [comment]
@mdubbyap thank you! Please let us know if there is anything we can do to help.

**Comment by dgriff-tools** [comment]
Hi @jk0 which kubernetes version and what is the host node OS?

**Comment by jk0** [comment]
@dgriff-tools k8s v1.2.2 / CoreOS-beta-1185.2.0-hvm

**Comment by dgriff-tools** [comment]
@jk0 Thanks!

**Comment by jk0** [comment]
@dgriff-tools thanks for taking a look at this for us. Are there any updates to share yet?

**Comment by posix4e** [comment]
Any updates

**Comment by dgriff-tools** [comment]
@posix4e sorry for the delay in update.  using coreos/k8s v1.2.2 I did reproduce.  still investigating and will update on findings.  this may take a bit of time due to complexity.

**Comment by jk0** [comment]
So far in my tests (today and yesterday) I have not been able to reproduce this in k8s 1.3.9.

**Comment by posix4e** [comment]
Amazing!

**Comment by dgriff-tools** [comment]
Based on some testing, the coreos-kubernetes versions starting with release v0.8.0 work without issue.  That would include k8s v1.3.2 and up.

In your coreos environment running k8s v1.2.2, is heapster running ok?

**Comment by jk0** [comment]
We've migrated to k8s v1.3.9, so this is no longer an issue for us.
